### ISSUE TITLE
Use a shared cached bundle for all repos to speed up travis builds

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-dev#101]
The bundle caching on travis has helped make our builds faster.  However, we still have to run a full `bundle install` when the build for `rspec-x` bundles for `rspec-y` in order to run the `rspec-y` specs.  For example, see this rspec-expectations build:

https://travis-ci.org/rspec/rspec-expectations/jobs/45419435

The main `bundle install` step took 4.27 seconds and didn't have to install any gems thanks to travis's bundle caching.  However, the "Running specs for rspec-core" step took 68.6 seconds, of which the specs themselves were only ~ 5 seconds of it.  The other 63 seconds were spent installing rspec-core's bundle, which isn't cached at all.

It would cut about a minute out of each build matrix entry if we could find a way to make travis's bundler caching apply to all the repos.  I'm not totally sure how to do this but I'm thinking that if we have a common bundle directory that all the repos use (e.g. `../vendor`, since they are all cloned as sibling directories) it would perhaps work.

**Comment by JonRowe** [comment]
Can this be closed with the merging of #103?

**Comment by myronmarston** [comment]
Yep.
