### ISSUE TITLE
Is this repo supposed to be used for RSpec 3 development also?

### ISSUE THREAD

**Issue by hugobarauna** [rspec/rspec-dev#105]
In this project's description it's written "Rspec-2 development environment". So, I'm in doubt if I can or if I should use this project for helping me contributing to RSpec 3.

Should I?

**Comment by myronmarston** [comment]
Yes, we use this project for RSpec 3 as well.  I updated the project description.

Contributors can certainly use this but don't have to.  A lot of the stuff it helps with--cutting releases, changing branches on all repos, updating the travis build scripts for all repos, etc--is stuff RSpec core folks primarily deal with but it can be helpful for contributors too, so use it or not, whichever you prefer :).
