### ISSUE TITLE
Custom formatter namespace

### ISSUE THREAD

**Issue by trans** [rspec/rspec-dev#108]
For a custom formatter I created, on the command line I have to do:

    rspec -r rspec/ontap.rb -f RSpec::TapY

If I try to put

    rspec -r rspec/ontap.rb -f TapY

I get an error:

    cannot load such file -- tap_y (LoadError)

But it sucks to have to put the `RSpec::` namespace for the `-f` option. I can't get rid of the namespace  because `TapY` already exists as another class. It would be nice if RSpec would automatically look in the RSpec namespace. Ideally, I think it would automatically look in module `RSpec::Core::Formatters`, then I could just put my custom formatter in that namespace.

The other option is to add a format name argument to the `register` method. That might be even better as it would decouple the format name used with `-f` from the actual name of the class.

**Comment by myronmarston** [comment]
Personally, I like the simplicity/straightforwardness of `-f` being the fully qualified formatter name.  We could look in `RSpec` and `RSpec::Core::Formatters` namespaces, but that adds complexity that I'm not (yet) convinced we need.

I think most people put these options in `.rspec` (or in `.rspec-local -- it's intended to be a git-ignored file of personal settings for a project), and then you don't to type anything beyond `rspec`.  If you don't what this formatter as your normal formatter, you could also create a file like `spec/use_ontap.rb`:

``` ruby
require 'rspec/ontop'
RSpec.configure do |c|
  c.add_formatter RSpec::TapY
end
```

...and then optionally load it from the command line with:

```
rspec -r use_ontop
```

(RSpec puts `spec` on the load path so you can directly require files relative to `spec`).

Does that meet your needs?

> The other option is to add a format name argument to the register method. That might be even better as it would decouple the format name used with `-f` from the actual name of the class.

This is an interesting idea that I'll want to think more about.  @JonRowe, what do you think about it?

BTW, for future reference, please open formatter issues in the rspec-core repo.

**Comment by trans** [comment]
> Does that meet your needs?

Yea, that's good approach. And really the more I think about it, it's not that big a deal. I tend to really like simple interfaces, so my first inclination is that "spec -f tapy" should just work. That would require namespace and path conventions, and yes some extra, more complex code. So I can appreciate the simplicity of implementation argument.

> BTW, for future reference, please open formatter issues in the rspec-core repo.

Ah, ok. Sorry.

**Comment by myronmarston** [comment]
> I tend to really like simple interfaces, so my first inclination is that "spec -f tapy" should just work.

If your formatter was named `Tapy` and was defined in a file requirable as `tapy`, then `rspec -f Tapy` would just work.  We do the `CamelCase` -> `snake_case` conversion if the named constant is not defined and attempt to require that.  For example, `rspec -f Fivemat` just works because the fivemat formatter is available via `require 'fivemat'`.  We just require formatter names to be fully qualified rather than assuming they are within any particular namespace.

> Ah, ok. Sorry.

Honestly, I don't mind much, it's more for your sake as the person reporting this issue, to have the issue on one of the issue lists that we look at regularly.  Issues reported here (rather than rspec-core, rspec-mocks or rspec-expectations as appropriate) tend to get missed when we are looking into what issues are open, so they can get lost in the shuffle and be left unaddressed.

Anyhow, it sounds like you're satisfied with the approaches discussed above so I'm going to close this.

**Comment by trans** [comment]
> If your formatter was named Tapy and was defined in a file requirable as tapy, then rspec -f Tapy would just work. 

And yet it can't be that simple because "tapy" (and also "tapj") is a general format and I have formatter plugins for other test frameworks too, so the actual require has to be more specific. If RSpec where to try to require `rspec/tapy` or `rspec-tapy` or something like that for `-f Tapy` then it wouldn't be a problem. Actually that would also be a bit cleaner too, as it would prevent just any old file from being required.

**Comment by myronmarston** [comment]
> And yet it can't be that simple because "tapy" (and also "tapj") is a general format and I have formatter plugins for other test frameworks too, so the actual require has to be more specific. If RSpec where to try to require rspec/tapy or rspec-tapy or something like that for -f Tapy then it wouldn't be a problem. Actually that would also be a bit cleaner too, as it would prevent just any old file from being required.

I get that.  I didn't mean to suggest that it should work for your case (sorry about that!); I took your question to mean "I wish RSpec supported using a custom formatter only through -f without having to specify -r" and I was trying to explain that it does in fact support that if you follow a standard CamelCase -> snake_case convention.

In your case, `rspec -f RSpec::Tapy` would work (no `-r` needed) if your formatter is defined in a file requirable `rspec/tapy`.  Not quite as terse as `rspec -f Tapy` but it skips the `-r` option.

Alternately, you might consider doing what Fivemat does: it supports Minitest, Cucumber, RSpec 1, RSpec 2 and RSpec 3 and `Fivemat` is a module with a `new` singleton method that forwards to the appropriately defined formatter class for the test framework being used, which it infers by a combination of checking how many args are passed (which varies a bit between test frameworks) and what test framework constants are defined.  See here:

https://github.com/tpope/fivemat/blob/v1.3.1/lib/fivemat.rb#L28

**Comment by trans** [comment]
>  get that. I didn't mean to suggest that it should work for your case 

No no, of course. I just wanted to be clear. I guess what I am saying in the end is simply that I think the convention would be better if it included a specific underlying reference to "rspec" in some fashion, instead of trying to require any class/path given to -f.

> Alternately, you might consider doing what Fivemat does

Interesting. I will look into that. Thanks.
