### ISSUE TITLE
Connection refused connecting to https://localhost/data

### ISSUE THREAD

**Issue by ror6ax** [rspec/rspec-dev#118]
Hi guys,
I get the following error when I run rspec on a chef recipe:
`[2015-03-05T13:15:42+01:00] ERROR: Connection refused connecting to https://localhost/data, retry 1/5`

Can you please advice?

**Comment by myronmarston** [comment]
RSpec doesn't make any HTTP connections.  Some tool you are using (perhaps chef?) is, and you'll have to dig into it to figure out a fix.  We can't advise on other tools, naturally.  Good luck!
