### ISSUE TITLE
Have a Code of Conduct for contributors to RSpec that is approved by the maintainers

### ISSUE THREAD

**Issue by samphippen** [rspec/rspec-dev#124]
I think it'd be better to borrow from others than write our own. Ones I particularly like (that we can borrow under their liecensing):

* http://www.rust-lang.org/conduct.html
* https://www.djangoproject.com/conduct/

I'm going to ping some people on  twitter to ask for comments and I think @rspec/rspec should agree on a CoC before we put one in to place. Let's have a discussion and see if any conclusions are drawn before we put anything in to place.

**Comment by samphippen** [comment]
Also: http://contributor-covenant.org/

**Comment by samphippen** [comment]
http://bundler.io/conduct.html

**Comment by myronmarston** [comment]
To add my voice to this: I'm very much in favor of adopting a code of conduct.

**Comment by sarahmei** [comment]
Sam asked me to comment, so here I am. :) I really like the idea of having a CoC. Some random things I like about the ones linked above:

* The Contributor Covenant's inclusion of "public spaces when an individual is representing the project or its community" in the list of places where the CoC applies.
* Rust's addition of "or similar personal characteristic" to the list of things they won't discriminate on.
* Bundler's note that the CoC applies to project maintainers as well as other contributors.
* Django's addition of "Advocating for, or encouraging, any of the above behavior" to the list of unacceptable behaviors.

One thing I would like to see addressed better in CoCs, that I don't see in any of the above, is an explicit statement that using insulting language around someone's intelligence or competence is not allowed. This is something I used to get a lot, and it was super demoralizing.

**Comment by myronmarston** [comment]
Thanks for helping us out with this, @sarahmei :).

> Some random things I like about the ones linked above:

These all sound good, and I'd be happy to see them included in our CoC.

> One thing I would like to see addressed better in CoCs, that I don't see in any of the above, is an explicit statement that using insulting language around someone's intelligence or competence is not allowed.

I'd like to see this included, as well.

> This is something I used to get a lot, and it was super demoralizing.

:cry:

**Comment by samphippen** [comment]
After reading all 4 codes of conduct I'd like to pull for a modified version of the Contributor Covenant because:

* It is very short and easy to understand
* It has clear reporting guidelines
* As @sarahmei pointed out it includes interactions in public (e.g. conferences, meetups)

I'd like to make two modifications to it, one is the intelligence/competence thing that @sarahmei pointed out and the other is taken from their own website which is the following text at the top:

```
Please note that this project is released with a Contributor Code of Conduct. By participating in this project you agree to abide by its terms.
```

Thoughts @rspec/rspec ?

**Comment by JonRowe** [comment]
Sounds good to me :)

**Comment by soulcutter** [comment]
Can I still call myself stupid? (/joke)

Definite :+1: on including this on the project. In my mind insulting intelligence/competence is covered by "derogatory comments or personal attacks" and "insults" being listed as examples of unacceptable behavior in http://contributor-covenant.org/version/1/1/0/

**Comment by cupakromer** [comment]
Really happy to see this :smiley_cat: 

> I'd like to pull for a modified version of the Contributor Covenant...I'd like to make two modifications to it, one is the intelligence/competence thing that @sarahmei pointed out and the other is taken from their own website which is the following text at the top:

:+1: We can also suggest these to the Contributor Covenant as well as submit a PR to them. The project is evolving and they are happy to discuss things publicly via issues and PRs. :smile:

Looking at the issues and PRs it seems they are in the process of formalizing the [release of v1.2.0](https://github.com/CoralineAda/contributor_covenant/pull/83/). There is some improved wording and clarification on some of the points raised above from other CoCs. Thoughts on this newer version and how we can improve on it?

  * Rust's addition of "or similar personal characteristic" to the list of things they won't discriminate on.

    _I do not see language such as this currently listed. I do not speak for the maintainers but it seems they are trying to be explicit when possible and v1.2.0 covers a longer list. We could suggest this addition. I'd like to see [bullying](https://github.com/CoralineAda/contributor_covenant/pull/79) and [class](https://github.com/CoralineAda/contributor_covenant/pull/82) get merged as well._
  * Bundler's note that the CoC applies to project maintainers as well as other contributors.

    _Currently covered under the v1.2.0 version._
  * Django's addition of "Advocating for, or encouraging, any of the above behavior" to the list of unacceptable behaviors.

    _I think this is a good PR to make. :heart:_

**Comment by cupakromer** [comment]
Having just re-read Rust's CoC I do like some of the explicit things they call out particularly for IRC; though I see that would apply well with the mailing list too. I also like how Bundler made the markdown links for contacts easier so the barrier to finding actual contact details was greatly reduced.

One thing we need to cover is that this applies to all repos hosted under https://github.com/rspec I think each repo should have a copy placed in it which we keep in sync with the dev build scripts. Also, we have several add-on gems hosted under `rspec/` which are not officially maintained by members of the core team. I think we need to be clear on how we are going to handle those repos as well.

**Comment by krainboltgreene** [comment]
This makes me so happy.

**Comment by myronmarston** [comment]
I think it's good to make sure the language in our CoC is adequate but on the flip side, I worry a bit about being too detailed.  Take the [bullying example](CoralineAda/contributor_covenant#79).  I would have thought that bullying is just one form of "public or private harassment", which is already mentioned.  Providing a super detailed list of the behaviors we consider to be unacceptable may have the opposite affect.  For example, "don't use racial slurs" pretty clearly covers all racial slurs, but if we said "don't use racial slurs x, y and z" and someone used another racial slur not listed, they could try to claim our CoC didn't prohibit it.

I don't think we're falling into that trap but the thought occurred to me.  Ultimately, as someone who hasn't been subject to online harassment I'm happy to defer on these matters to those who have.

> One thing we need to cover is that this applies to all repos hosted under https://github.com/rspec I think each repo should have a copy placed in it which we keep in sync with the dev build scripts. Also, we have several add-on gems hosted under rspec/ which are not officially maintained by members of the core team. I think we need to be clear on how we are going to handle those repos as well.

This is a good point I hadn't thought of.  We should reach out to the folks who maintain those gems (@palfvin / @seuros / @thomas-holmes / @hugobarauna) and get them on board.

That said, I don't think that needs to be fully resolved before we forge ahead with adding the CoC to the repos we maintain.

**Comment by seuros** [comment]
Unless the CoC is different for some repos, we could have a repo just for the CoC and git submodule it into all the gems. That way, we will have always a centralized way to update it.

**Comment by JonRowe** [comment]
I'd rather we didn't go down the sub module route, it's an unnecessary complication, we can just use this repo to update it across all repos like we do with travis.

**Comment by cupakromer** [comment]
> I worry a bit about being too detailed. Take the bullying example. I would have thought that bullying is just one form of "public or private harassment", which is already mentioned. Providing a super detailed list of the behaviors we consider to be unacceptable may have the opposite affect.

Ah, missed that bullet point when I was reviewing last night. Agreed that I would classify bullying under that point. I also tend to prefer a broader list. I defer to those running the project as I trust and value their informed judgment on these matters.

> I'd rather we didn't go down the sub module route, it's an unnecessary complication, we can just use this repo to update it across all repos like we do with travis.

I'd rather not go the sub-module route. I'm not sure the other gem repos use rspec-dev to keep their build setup in sync. If they chose too that's great, if not, I respect that decision. If the maintainers wish to mirror and uphold the final agreed upon CoC, I'd be happy to update the Rake task for submitting PRs to treat those repos differently if that would be beneficial.

**Comment by samphippen** [comment]
It is my intention to write a draft code of conduct over the coming weekend, which will be largely derived from the contributor covenant. I'd like to get an @rspec/rspec vote on that once it's done.

**Comment by myronmarston** [comment]
> It is my intention to write a draft code of conduct over the coming weekend, which will be largely derived from the contributor covenant. I'd like to get an @rspec/rspec vote on that once it's done.

:+1:

**Comment by samphippen** [comment]
Regarding specificity of language, there's a simple trick the lawyers use which works for this all time time. For example "Don't use racial slurs, including, but not limited to: x,y  and z.".  Providing examples can help strengthen, as long as it's explicit that's not the whole list. Anyway, I'm going to do it now and report back.

**Comment by samphippen** [comment]
Here's what I've got.

There are two (very minor) changes from the Contributor Covenant.

1. an addition of an "include, but not limited to" in the paragraph about examples of unacceptable behaviour
2. an addition of "other similar personal characteristic" in the paragraph listing personal characteristics that people should not be harassed because of (this sentence is weird and meta)

```
# Contributor Code of Conduct

Please note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.

As contributors and maintainers of this project, we pledge to respect all
people who contribute through reporting issues, posting feature requests,
updating documentation, submitting pull requests or patches, and other
activities.

We are committed to making participation in this project a harassment-free
experience for everyone, regardless of level of experience, gender, gender
identity and expression, sexual orientation, disability, personal appearance,
body size, race, ethnicity, age, religion or similar personal characteristic.

Examples of unacceptable behavior by participants include, but are not limited
to, the use of sexual language or imagery, derogatory comments or personal
attacks, trolling, public or private harassment, insults, or other
unprofessional conduct.

Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct. Project maintainers who do not
follow the Code of Conduct may be removed from the project team.

This code of conduct applies both within project spaces and in public spaces
when an individual is representing the project or its community.

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by opening an issue or contacting one or more of the project
maintainers.

This Code of Conduct is adapted from the [Contributor
Covenant](http://contributor-covenant.org), version 1.1.0, available at
[http://contributor-covenant.org/version/1/1/0/](http://contributor-covenant.org/version/1/1/0/)
```

Thoughts @rspec/rspec ?

**Comment by myronmarston** [comment]
LGTM in general, although the intro paragraph reads awkwardly to me:

> Please note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.

The CoC has more to do with _development_ than just with project releases so saying the it's "released with a CoC" seems very odd.  "Please note" seems like an odd way to start the document, too.  Maybe something like this instead?

> For the purposes of building a welcoming, harassment-free community that values contributions from anyone, the RSpec project has adopted the following code of conduct.  All contributors and participants (including maintainers!) are expected to abide by its terms.

**Comment by krainboltgreene** [comment]
I like that a lot.

On Sun, Jul 5, 2015 at 1:55 AM, Myron Marston <notifications@github.com>
wrote:

> LGTM in general, although the intro paragraph reads awkwardly to me:
>
> Please note that this project is released with a Contributor Code of
> Conduct.
> By participating in this project you agree to abide by its terms.
>
> The CoC has more to do with *development* than just with project releases
> so saying the it's "released with a CoC" seems very odd. "Please note"
> seems like an odd way to start the document, too. Maybe something like this
> instead?
>
> For the purposes of building a welcoming, harassment-free community that
> values contributions from anyone, the RSpec project has adopted the
> following code of conduct. All contributors and participants (including
> maintainers!) are expected to abide by its terms.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rspec/rspec-dev/issues/124#issuecomment-118588521>.
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by JonRowe** [comment]
I like @myronmarston's suggested improvements but looks good otherwise

**Comment by myronmarston** [comment]
I updated #125 with the CoC discussed here, and have pushed it out to all repos.

**Comment by cupakromer** [comment]
:blue_heart: :blue_heart:

**Comment by thomas-holmes** [comment]
Thanks!

**Comment by samphippen** [comment]
YAAAAAAAAAAAAAAAAAAAAAAAAAAS

**Comment by yujinakayama** [comment]
:+1:
