### ISSUE TITLE
`expect_any_instance_of` throwing deprecation warning

### ISSUE THREAD

**Issue by onetwopunch** [rspec/rspec-dev#126]
I have the test:
```
24:   it 'should log to STDOUT' do
25:     expect_any_instance_of(Logger).to receive(:error).with("WAT")
26:     Logplexer.error("WAT")
27:   end
```

Which uses the new expect syntax ( so far as I know ) yet I still get the following deprecation warning:

```
Deprecation Warnings:

Using `any_instance` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. 
Use the new `:expect` syntax or explicitly enable `:should` instead. 
Called from /Users/rcanty/Workspace/logplexer/spec/logplexer_spec.rb:25:in `block (2 levels) in <top (required)>'.
```

The relevant portion of my `Gemfile.lock` looks like this: 

``` 
rspec (3.3.0)
  rspec-core (~> 3.3.0)
  rspec-expectations (~> 3.3.0)
  rspec-mocks (~> 3.3.0)
rspec-core (3.3.1)
  rspec-support (~> 3.3.0)
rspec-expectations (3.3.0)
  diff-lcs (>= 1.2.0, < 2.0)
  rspec-support (~> 3.3.0)
rspec-mocks (3.3.1)
  diff-lcs (>= 1.2.0, < 2.0)
  rspec-support (~> 3.3.0)
rspec-support (3.3.0)
```

**Comment by myronmarston** [comment]
Thanks for reporting this.  However, I can't repro.  I put together a spec file like this:

``` ruby
require 'logger'

class Logplexer
  def self.error(msg)
    Logger.new($stdout).error(msg)
  end
end

RSpec.describe Logplexer do
  it 'should log to STDOUT' do
    expect_any_instance_of(Logger).to receive(:error).with("WAT")
    Logplexer.error("WAT")
  end
end
```

...but it doesn't trigger the warning you are seeing.  There's something different about your project that I'm not able to guess.  Any chance you could provide a runnable example that repros this?  gist.github.com works well for sharing small little examples  :).

**Comment by onetwopunch** [comment]
@myronmarston thanks for the quick reply. Sure, you could clone the repo at https://github.com/Fullscreen/logplexer I just updated master to include the tests I was having issues with.

**Comment by myronmarston** [comment]
After cloning your repo, running `bundle install` and `bundle exec rspec`, I get this:

```
Deprecation Warnings:

Using `should_receive` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/myron/code/rspec-scratch/logplexer/spec/logplexer_spec.rb:62:in `block (2 levels) in <top (required)>'.
```

Looking at [`spec/logplexer_spec.rb:62`](https://github.com/Fullscreen/logplexer/blob/26879c2400a58b80fbc8e4559eef2c99a849ebe3/spec/logplexer_spec.rb#L62), I see:

``` ruby
Honeybadger.should_receive(:notify).with( exception, {} )
```

...which is using the old syntax and RSpec is giving you a deprecation warning.  I don't get a deprecation warning for line 25 like you said you got above.

If you want to continue using the old syntax, explicitly enable it:

``` ruby
RSpec.configure do |config|
  config.mock_with :rspec do |mocks|
    mocks.syntax = :should
  end
end
```

Otherwise upgrade to the new syntax and the warning will go away.  [Transpec](http://yujinakayama.me/transpec/) will do the syntax conversion for you.  Our recommended upgrade workflow is documented:

http://rspec.info/upgrading-from-rspec-2/

**Comment by onetwopunch** [comment]
@myronmarston Geez I totally missed that thanks. On my env it was telling me line 25. Thanks for the help :+1:

**Comment by myronmarston** [comment]
> @myronmarston Geez I totally missed that thanks. On my env it was telling me line 25. Thanks for the help

If you're still seeing the warning originated from line 25 then there may be an RSpec bug here but until we can repro there's nothing we can do to fix it.  Are you still seeing the warning from line 25?

**Comment by onetwopunch** [comment]
@myronmarston I just checked it and after changing the line you pointed out I'm not receiving the deprecation warning. Thanks again man
