### ISSUE TITLE
False positives after upgrade to RSpec 3.1

### ISSUE THREAD

**Issue by mcbsys** [rspec/rspec-dev#129]
I hope this is the right place to report this.

I used Transpec 3.1.0 a few months back to convert to RSpec 2.99 and subsequently 3.1.0. The overall experience was very good but recently I have noticed that Transpec seems to have missed a few tests and unfortunately, RSpec silently passes these tests, so I only discover the issues by chance.

I'm reporting the Transpec issue separately (https://github.com/yujinakayama/transpec/issues/106). Here I just want to ask if RSpec could somehow flag old / incorrect syntax rather than passing all tests in the old syntax. For example,

`it { @user.notifications_pending == 0 }`
`specify { new_user.notification_interval_secs == 3600 }`

Both of these test pass just fine. If I change them to 

`it { @user.notifications_pending == 9 }`
`specify { new_user.notification_interval_secs == 600 }`

they also pass. In other words, they pass regardless of the value, so they are not testing anything. If I manually re-write them:

`it { expect(@user.notifications_pending).to eq(0) }`
`specify { expect(new_user.notification_interval_secs).to eq(3600) }`

they only pass when correct values are supplied.

**Comment by myronmarston** [comment]
``` ruby
it { @user.notifications_pending == 0 }
```

This was never asserting anything other than the fact that calling `==` does not raise an error.  On 2.x and 3.x it behaves exactly the same, and transpec should not update it.  The old syntax (which I think you meant to use?) was:

``` ruby
it { @user.notifications_pending.should == 0 }
```

And if you had that in 2.x, when you use transpec to upgrade to 3.x it would correctly upgrade the syntax.

We have a feature on our roadmap (rspec/rspec-core#759) that would help in this situation by warning or erroring when you do not use any expectations in an example...but that really has nothing to do with the upgrade process.  It's just a new feature we may add at some point.

I don't think there's anything actionable for us to do here (beyond the feature mentioned above), so I'm going to close this.

**Comment by mcbsys** [comment]
@myronmarston, thanks for your prompt reply. You are absolutely right, the old tests were missing the `should`! My bad for not being more religious about testing the test (making sure a test fails before it succeeds)

That enhancement sounds like a great idea. With nearly 2000 tests, it's hard to check for a missing `expect` here and there. For now, I'm searching for `==`, as that probably means the "test" was skipped by Transpec because it wasn't asserting anything.
