### ISSUE TITLE
Updating Rubocop to 0.32.1 issues

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-dev#134]
While at [Ruby for Good](http://rubyforgood.com) the team is looking to get familiar with the code base by improving the spec suite a little. When running `script/run_build` with Ruby 2.2, the most recent version, Rubocop does not run. This can/will cause PRs to be submitted with simple cop failures.

This is due to two issues:
- `Gemfile` omitting `:ruby_22` from the list of platforms
- Old version of Rubocop v0.23.0 not supporting Ruby 2.2

During the process of updating to Rubocop v0.32.1 (the latest) there have been several issues we did not know how to deal with. Below is a sample, from rspec-support, that lists the problematic cops and some places where they appear:

> Operator should be surrounded with a single space

```
  lib/rspec/support/caller_filter.rb:72:23: C: Operator *= should be surrounded with a single space.
            increment   *= 2 # The choice of two here is arbitrary.
                        ^^
  lib/rspec/support/method_signature_verifier.rb:98:48: C: Operator + should be surrounded with a single space.
            @max_non_kw_args = @min_non_kw_args  + optional_non_kw_args
                                                 ^
```

> Pass symbol to proc as an argument to message

```
  lib/rspec/support/differ.rb:194:9: C: Pass &:to_s as an argument to sort_by instead of a block.
          formatted_hash.keys.sort_by { |k| k.to_s }.map do |key|
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  lib/rspec/support/hunk_generator.rb:27:9: C: Pass &:chomp as an argument to map! instead of a block.
          @expected.split("\n").map! { |e| e.chomp }
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

> Prefer single-quoted strings inside interpolations.

```
  lib/rspec/support/method_signature_verifier.rb:44:88: C: Prefer single-quoted strings inside interpolations.
                parts << "optional keyword args (#{@optional_kw_args.map(&:inspect).join(", ")})"
                                                                                         ^^^^
  lib/rspec/support/object_formatter.rb:60:43: C: Prefer single-quoted strings inside interpolations.
            time.strftime("#{TIME_FORMAT}.#{"%09d" % time.nsec} %z")
                                            ^^^^^^
```

> Do not use parallel assignment

```
  lib/rspec/support/version_checker.rb:8:9: C: Do not use parallel assignment.
          @library_name, @library_version = library_name, library_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

> Non-local exit from iterator

```
  lib/rspec/support/spec/library_wide_checks.rb:112:5: W: Non-local exit from iterator, without return value. next, break, Array#find, Array#any?, etc. is preferred.
      return if failing_lines.empty?
      ^^^^^^
  lib/rspec/support/spec/library_wide_checks.rb:123:5: W: Non-local exit from iterator, without return value. next, break, Array#find, Array#any?, etc. is preferred.
      return if failing_lines.empty?
      ^^^^^^
```

/cc @rspec/rspec

**Comment by cupakromer** [comment]
After reviewing these errors my thoughts are:

> Operator should be surrounded with a single space

Very on the fence here. In these particular instances here I don't really see the benefit of aligning the operators. Though, I can see, and appreciate, the alignment with a longer list.

The cop default is:

```yaml
Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
    - '='
    - '=>'
```

While on the fence, I'm okay with that list for now and keeping this cop enable.


> Pass symbol to proc as an argument to message

I was a long day so I likely missed it. I thought we benchmarked this as the block form was faster. If that's true I say we disable this or invert it when possible.

> Prefer single-quoted strings inside interpolations.

Disable.

> Do not use parallel assignment

At first I didn't see an issue here and wanted to disable. Rubocop claims a perf boost:

  > Style/ParallelAssignment:
  >   Description: >-
  >                   Check for simple usages of parallel assignment.
  >                   It will only warn when the number of variables
  >                   matches on both sides of the assignment.
  >                   This also provides performance benefits
  >   StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#parallel-assignment'
  >   Reference: 'https://github.com/JuanitoFatas/fast-ruby#parallel-assignment-vs-sequential-assignment-code'
  >   Enabled: true

If this is true, I vote for keeping this enabled.

> Non-local exit from iterator

I could be missing something, but this seems broken.

**Comment by soulcutter** [comment]
I haven't looked at all these examples yet, but the proc one stood out to me. 

https://github.com/JuanitoFatas/fast-ruby/blob/master/code/proc-and-block/block-vs-to_proc.rb

I suspect this performance has changed in more-recent versions of Ruby? Was perf in older rubies bad enough to justify going forward enforcing this cop or even its inverse? Or I wonder if benching our app specifically still bears this out as a win? Maybe that's another cop to disable.

You can disable cops for just specific instances with comments, which could address any of these like the single-space-assignment while still allowing for exceptional cases. Not sure whether folks consider that too aesthetically grating though.

Bradley Schaefer

**Comment by cupakromer** [comment]
I looked into the parallel assignment. The benchmark is flawed. Parallel assignment appears faster:

```ruby
require 'benchmark/ips'

def slow
  a, b, c, d, e, f, g, h = 1, 2, 3, 4, 5, 6, 7, 8
end

def fast
  a = 1
  b = 2
  c = 3
  d = 4
  e = 5
  f = 6
  g = 7
  h = 8
end

def parallel_assign
  a, b, c, d, e, f, g, h = 1, 2, 3, 4, 5, 6, 7, 8
  nil
end

def sequential_assign
  a = 1
  b = 2
  c = 3
  d = 4
  e = 5
  f = 6
  g = 7
  h = 8
  nil
end

Benchmark.ips do |x|
  x.report('Parallel Assignment (flawed)            ') { slow }
  x.report('Sequential Assignment          ') { fast }
  x.report('Parallel Assignment no return  ') { parallel_assign }
  x.report('Sequential Assignment no return') { sequential_assign }
  x.compare!
end

__END__


Original benchmark from:
https://github.com/JuanitoFatas/fast-ruby#parallel-assignment-vs-sequential-assignment-code
> Parallel Assignment allocates an extra array.
def slow
  a, b, c, d, e, f, g, h = 1, 2, 3, 4, 5, 6, 7, 8
end

def fast
  a = 1
  b = 2
  c = 3
  d = 4
  e = 5
  f = 6
  g = 7
  h = 8
end

Benchmark.ips do |x|
  x.report('Parallel Assignment')   { slow }
  x.report('Sequential Assignment') { fast }
  x.compare!
end

However that logic is flawed. They claim the parallel assignment allocates some
extra array. This is not true. The message return is what allocates the array.
The updated benchmark shows these side-by-side and the parallel only assignment
appears faster.


$ ruby -v assignment.rb
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

Calculating -------------------------------------
Parallel Assignment
                        63.218k i/100ms
Sequential Assignment
                        83.912k i/100ms
Parallel Assignment no return
                        86.713k i/100ms
Sequential Assignment no return
                        83.128k i/100ms
-------------------------------------------------
Parallel Assignment
                          1.858M (± 7.6%) i/s -      9.230M
Sequential Assignment
                          3.833M (± 6.9%) i/s -     19.132M
Parallel Assignment no return
                          4.948M (± 8.2%) i/s -     24.626M
Sequential Assignment no return
                          3.678M (± 6.2%) i/s -     18.371M

Comparison:
Parallel Assignment no return  :  4948069.2 i/s
Sequential Assignment          :  3833383.3 i/s - 1.29x slower
Sequential Assignment no return:  3678282.7 i/s - 1.35x slower
Parallel Assignment            :  1858413.4 i/s - 2.66x slower
```

**Comment by cupakromer** [comment]
Running the benchmark for `Symbol#to_proc` and a block confirmed that the `Symbol#to_proc` is faster. I didn't see anything directly flawed with the benchmark. Here is a gist of the benchmark I used and a summary of the output.

The only difference was small arrays (size 10) often were slightly faster using the block form. Though this was a minor difference in most cases.

Unless we can find a condition where this isn't true I vote we switch to the symbol to proc.

**Comment by myronmarston** [comment]
@cupakromer -- the parallel assignment benchmark is interesting, but I'd argue that we should still stop using parallel assignment (except for destructuring; that's obviously OK).  Adding a `nil` at the end of `initialize` is _not_ idiomatic ruby (in my 8 years of doing Ruby, I've never seen any one do that) and to get the perf benefit your benchmark shows, you have to do the non-idomatic thing and add the `nil` -- but it can be very easy to forget.  When you remember and add the `nil`, the perf improvement is modest, but when you forget to add it, the perf decline is quite large.  Doesn't seem worth the risk, IMO.  I don't want to be favoring a style that forces us to remember to add extra lines of non-idiomatic code to prevent problems.  I also think that parallel assignment is generally hard to work with than sequential assignment.

**Comment by cupakromer** [comment]
> Adding a `nil` at the end of `initialize` is not idiomatic ruby

I would agree. I wasn't viewing the benchmark that way. I was viewing it as simple assignment in a normal method / block condition where that LOC is not a return value. I'm not sure I've ever written a parallel assignment statement which is also a the LOC that returns from the method. If you're returning what's the point of a local variable assignment?

You bring up an interesting point with `initialize`. Does `initialize` internally follow standard implicit return rules? The return of `new` is always the object and never what the method would appear to return. It shouldn't take long at all to put that together and run it tomorrow.

> I also think that parallel assignment is generally hard to work with than sequential assignment.

I think that depends. Using parallel assignment for swapping variables is fairly idiomatic Ruby. Though I can't say I've seen parallel assignments larger than three variables. I would agree that would be difficult to manage.

**Comment by cupakromer** [comment]
So `initialize` still has implicit returns even though that value is always ignored. The benchmark has been improved / updated to provided a bit better review and is in: https://github.com/rspec/rspec-support/pull/233

In the majority of conditions and across the most Rubies sequential assignment is faster. So we should follow that. The occasional usage of parallel assignment for swapping variables is more performant than the sequential alternative, so if we use that we can just tell the cop to ignore it.

The only outstanding cop to discuss is the symbol to proc. The benchmarks show that Ruby 1.9 and 2.x sym-to-proc is faster. The block way is faster on Ruby 1.8.7, REE, and JRuby. My personal vote is to enable this cop and start using sym-to-proc.

**Comment by myronmarston** [comment]
I'm in favor of symbol-to-proc.

**Comment by JonRowe** [comment]
Hey if it's quicker lets rock it :)

**Comment by olleolleolle** [comment]
Is this still current, or can it be closed?

**Comment by pirj** [comment]
We're far behind the edge RuboCop, but 0.52.1 is more recent than 0.32.1, so I believe this may be closed safely.
