### ISSUE TITLE
Failure testing action show in controller.

### ISSUE THREAD

**Issue by RomarioLopezC** [rspec/rspec-dev#162]
Failure:

`Failures:

  1) ScalesController client user GET #show renders the :show template
     Failure/Error: expect(response).to render_template :show
       expecting <"show"> but rendering with <["layouts/application"]>
     # ./spec/controllers/scales_controller_spec.rb:303:in block (4 levels) in <top (required)>
`

rpec:
`
it 'renders the :show template' do
        scale = create(:scale)
        get :show, id: scale
        expect(response).to render_template :show
      end
`

Controller:

`def show
    @scale = Scale.find(params[:id])
  end
`

**Comment by JonRowe** [comment]
This repo contains tools for managing the rspec repos, and this is clearly an `rspec-rails` request for help,  we can't debug minimal examples like this, as theres a million and one reasons why Rails wouldn't render  the show template here. If you can produce a minimal rails app demonstrating this issue then open an issue over at https://github.com/rspec/rspec-rails linking to it.
