### ISSUE TITLE
rspec example loses the to_return portion of a stub?

### ISSUE THREAD

**Issue by tgmerritt** [rspec/rspec-dev#172]
Please check the stackoverflow issue here:

https://stackoverflow.com/questions/40688496/stub-request-method-loses-the-to-return-portion

I'm not good enough to get you an entirely separate app with just this test - you can see what rspec tells me to stub, if you stub it out, then run a spec, it appears to forget about the "and_return" portion of the stub.  Then it fails for obvious reasons.  I can't see what I'm doing wrong - I've copied / pasted the message directly from the terminal that rspec suggests.

**Comment by tgmerritt** [comment]
This appears to be happening with multiple such stub_reqeusts in different specs.

Here is a list of the rspec related gems in Gemfile.lock:

```
rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-rails (3.5.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
```

**Comment by myronmarston** [comment]
`stub_request` is not provided by RSpec.  It is provided by [webmock](https://github.com/bblimke/webmock).  If you're having problems with it, please report them to the webmock maintainers.  We don't have the capacity to help RSpec users troubleshoot issues they are having with other gems.
