### ISSUE TITLE
How to update JRuby version?

### ISSUE THREAD

**Issue by PragTob** [rspec/rspec-dev#180]
Hey there as mentioned earlier and [noted](https://github.com/rspec/rspec-dev/pull/179#issuecomment-315527613) updating JRuby might have some work, but not as much. (ref: #179 )

Question:

How would one best do that? The `.travis.yml` is updated here, then you make PRs to all repos. In those we then need to fix the JRuby errors, pending specs, whatever. Assuming they can't be fixed in a way that they work with the old JRuby version as well, fixes would need to be on those branches.

So, do I make a PR against the branch with your PR then? :)

**Comment by myronmarston** [comment]
The simplest way is probably to make individual PRs against each repo (core/expectations/mocks/support), bumping the jruby version in `.travis.yml` in each and fixing any issues.  There's nothing wrong with updating `.travis.yml` in the individual projects as long as you're aware that the file is usually generated from this repo.  Once you've updated each repo, you can make the same change here so when `.travis.yml` is generated in the future it has the new JRuby version.

Alternately, you can try running our `travis:create_pr_with_updates` or `travis:update_files` rake tasks to start with the change here and then make your own branches in each repo.  Whatever you find easiest is fine :).
