### ISSUE TITLE
CI builds are failing due to lack of test coverage with SimpleCov 0.15

### ISSUE THREAD

**Issue by yujinakayama** [rspec/rspec-dev#182]
Currently our CI builds in master are failing:

* https://travis-ci.org/rspec/rspec-core/builds/264962032
* https://travis-ci.org/rspec/rspec-expectations/builds/264962030
* https://travis-ci.org/rspec/rspec-mocks/builds/264962247
* https://travis-ci.org/rspec/rspec-support/builds/264569271

These are caused by lack of test coverage with [SimpleCov 0.15](https://github.com/colszowka/simplecov/blob/v0.15.0/CHANGELOG.md):

```
$ cd repos/rspec-core
$ grep 'simplecov (0' Gemfile.lock
    simplecov (0.14.1)
$ bundle exec ./script/rspec_with_simplecov | grep 'Coverage report'
Coverage report generated for RSpec to /Users/nkymyj/Projects/rspec-dev/repos/rspec-core/coverage. 4628 / 4628 LOC (100.0%) covered.
$ bundle update > /dev/null
$ grep 'simplecov (0' Gemfile.lock
    simplecov (0.15.0)
$ bundle exec ./script/rspec_with_simplecov | grep 'Coverage report'
Coverage report generated for RSpec to /Users/nkymyj/Projects/rspec-dev/repos/rspec-core/coverage. 15604 / 15808 LOC (98.71%) covered.
```

I haven't yet dug into this, so I'm not sure if this is a _bug fix_ or a _bug_ in SimpleCov.

**Comment by myronmarston** [comment]
It looks like the newer version of simplecov is considering a lot more lines of code (15K instead of 4K); perhaps the filters that are meant to exclude dependencies from consideration are not working? A comparison of the list of files would be illuminating.

**Comment by yujinakayama** [comment]
https://github.com/rspec/rspec-core/pull/2457

**Comment by JonRowe** [comment]
I think this is closed, as its core that was the issue yes?

**Comment by yujinakayama** [comment]
CI builds are still failing but now it's caused by a warning from JVM: #184
