### ISSUE TITLE
Move docs off of relishapp onto ~~Cucumber Pro~~ Jam

### ISSUE THREAD

**Issue by mattwynne** [rspec/rspec-dev#199]
Hello,

We at Cucumber Ltd have a strategic plan to sunset https://relishapp.com and move everyone over to https://cucumber.io/jam

The RSpec project is our favourite user of Relish (it was @dchelimsky who was the main product owner right back when we first built it) and we're going to do our utmost to support you through the transition.

There's still one feature I think you'll need us to add to Cucumber Pro before you'll want to move over fully, which is the ability to group projects into "products" as you can currently do with the equivalent "publisher" on http://relishapp.com/rspec. That's on our roadmap for the next couple of months, so I thought it was time to flag this up with you and start testing everything else out.

Anyway, I'm making this ticket to start the conversation. If you'd like to get set up with an account on pro and try publishing docs to both Relish and Pro for an interim period, I'm available to walk one of you through it.

Let me know how you'd like to proceed.

**Comment by myronmarston** [comment]
Hi @mattwynne!

Thanks for bringing this to our attention.  I think publishing to both services for a period sounds like the way to go.  Are there any docs written up for how to migrate from relish to cucumber pro?  I know there are other projects on relish that will need to migrate (VCR, for example) so the audience for this process is more than just us.

Once you shut down relish, do you have any plans to redirect to cucumber pro?  There are lots of links out in the wild to the RSpec relish docs, and it would be unfortunate to break all those links.

One other thought: after rebuilding the rspec.info site, we moved the API docs there (as yard makes it easy to generate the docs as static html).  Would it be feasible to do something similar for our cukes using cucumber pro's gherkin to html converter or something?  Or are there significant features of cucumber pro that would be applicable to us that we'd be giving up by going that route (if it is in fact feasible)?

**Comment by mattwynne** [comment]
Hi @myronmarston thanks for getting back to me so fast.

There are no docs for this yet, no. I plan to write to all the Relish users, but I wanted to give you folks a more personal service.

Do you fancy popping into our [Slack](https://cucumber.io/support#slack) and I can help walk you through it?

**Comment by myronmarston** [comment]
It's kinda hit and miss when I have time to work on RSpec but I'll try stopping by soon.

**Comment by mattwynne** [comment]
Actually, if you can give me sufficient permissions on the RSpec repos to add webhooks, I can do it for you. Would that be helpful?

**Comment by myronmarston** [comment]
@mattwynne sure!  Let me see if I can figure that out.

**Comment by myronmarston** [comment]
@mattwynne you should have access now.  One thing to bear in mind is that we're likely going to be combining repositories soon (see rspec/rspec-core#2509).  Not sure what affect that'll have on our use of webhooks for this but hopefully there'll be a straightforward path forward.

**Comment by mattwynne** [comment]
cc @tooky

**Comment by benoittgt** [comment]
I am available to work on the migration if needed. @mattwynne what is the status of "group projects"? 

Thanks

**Comment by mattwynne** [comment]
Thanks for the offer @benoittgt!

So, with the [release of CucumberStudio](https://cucumber.io/blog/news/hiptest-plus-jam-equals-cucumberstudio/) the goalposts for this have moved a little bit.

@tooky is managing the product these days and is best placed to talk about the way forward.

**Comment by benoittgt** [comment]
Little ping on this. @tooky can you help me?

**Comment by tooky** [comment]
@benoittgt we're not ready to go on this right now - we haven't really started to look at supporting public projects in CucumberStudio so I can't give you a time line yet.

**Comment by benoittgt** [comment]
Hello @tooky 

By any chance do you have any updates? 

Cheers

**Comment by pirj** [comment]
@tooky Our users started complaining that Relish app stopped working. What is the quickest way to migrate our docs to cucumber.io?

**Comment by mattwynne** [comment]
Relish should be back up now folks, sorry for the hitch.

**Comment by heathd** [comment]
https://relishapp.com/ seems to be offline again?

Error message:

```
Application error

An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail
```

<img width="806" alt="Screenshot 2023-12-10 at 15 20 55" src="https://github.com/rspec/rspec-dev/assets/61065/c4babd3e-5d16-4963-b1e7-f58737a8703f">

**Comment by pirj** [comment]
We’ve moved our docs to https://rspec.info

**Comment by heathd** [comment]
Playing catchup... reading https://mattwynne.net/relish and https://ruby.social/@katafrakt/109947941334464914

Thanks @pirj for your reply!

**Comment by JonRowe** [comment]
You can access the generated docs on this page specifically: https://rspec.info/documentation/

The drop downs for "examples" take you to similar url'd pages that matched the old relish hosted gherkin.
