### ISSUE TITLE
Augmented output for `config.around(:suite)`

### ISSUE THREAD

**Issue by ioquatix** [rspec/rspec-dev#205]
I am working on a coverage tool for RSpec. I want to report coverage errors as part of RSpec.

Is there some way I can hook into the RSpec output formatting?

Is there documentation regarding this?

Something like this:

```
config.before(suite) do
    coverage.enable
end

config.after(:suite) do
    coverage.disable
    statistics = coverage.statistics
    # log coverage issues, perhaps calling something like this
    expect(statistics).to be_complete
    # or doing it per-file?
end
```

**Comment by myronmarston** [comment]
> I want to report coverage errors as part of RSpec.

What is a coverage error?  I've never heard that term before.

> Is there some way I can hook into the RSpec output formatting?

The standard way to hook into output formatting is to write a custom formatter.  You have complete control over it.

> Is there documentation regarding this?

https://relishapp.com/rspec/rspec-core/v/3-7/docs/formatters/custom-formatters
http://rspec.info/documentation/3.7/rspec-core/RSpec/Core/Formatters/Protocol.html

> Something like this:

I don't understand the snippet.

* Around hooks have to yield control at some point--where is that happening in your example?
* What does `coverage.finish` do?
* What are the semantics of `statistics.complete?`

**Comment by ioquatix** [comment]
Ah my bad it should have been after not around :) I will check the links thanks

**Comment by ioquatix** [comment]
> What is a coverage error? I've never heard that term before.

So, a coverage error would be an error because the coverage wasn't good enough. The way I'm thinking about it right now is a user specified threshold, i.e. 80% coverage minimum. When test coverage falls below that, the test suite will fail due to a coverage error.

`statistics.complete?` just means that coverage was 100%. It's an example. There might be a better way of doing this.

So, I'm not after changing the format of the output, but I'm interested in generating a pseudo-spec which executes and generates said output.

I guess what I need to do is get the current formatter, and then interact with it like a spec. Is this reasonable?

**Comment by ioquatix** [comment]
So, here is what I got so far:

```
Covered::Wrapper
  passes #mark through
  passes #enable through
  passes #disable through
  passes #each through
* 9 files checked; 184/184 lines executed; 100.0% covered.

An error occurred in an `after(:suite)` hook.
Failure/Error: expect(statistics).to_not be_complete
  expected `#<Covered::Statistics:0x00007fd8761e8240 @count=9, @executable_count=184, @executed_count=184>.complete?` to return false, got true
# ./lib/covered/rspec.rb:41:in `block (2 levels) in <top (required)>'
```

It's not bad, I can customise the expectation error message, which should be okay.

What I want is a way to give informal output before the errors. Is that possible?

Finally, in the case that there is a coverage error, I want to do my own terminal highlighting. Essentially, I want to print out the code in question, covered lines green and failed lines red. I already have that working, but not via RSpec.

**Comment by ioquatix** [comment]
Hmm, so just to finish off tonight, here is the successful output:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/30030/42159936-a5f9f3d8-7e49-11e8-929b-8ea7fd3193eb.png">

Here is failed output:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/30030/42160707-5a5f5ba4-7e4c-11e8-9644-d5aa997c30e0.png">

Basically, I'd like to make the formatting as awesome as possible and integrate really well with RSpec. Maybe that's not possible, but hopefully you can see what I'm trying to achieve.

**Comment by ioquatix** [comment]
The other option is I just use an `at_exit` hook (ugh) and do everything after rspec finished. But, I'd rather have awesome integration.

**Comment by myronmarston** [comment]
Thanks for the detail; now I'm closer to understanding what you're trying to achieve.

I think the simplest way to achieve what you're looking for is to register a custom formatter and handle the `start_dump` notification.  That exists for cases like your where you want to produce some extra output between the test suite finishing and the printing of all the failures and the summary.

**Comment by ioquatix** [comment]
Okay, I've almost got this working how I want. Is there some way to cause RSpec to fail with an error form `start_dump`? One option is just to call `exit`, but is there a better approach?

**Comment by myronmarston** [comment]
You can use `RSpec.configuration.reporter.notify_non_example_exception`:

https://github.com/rspec/rspec-core/blob/v3.7.1/lib/rspec/core/reporter.rb#L156-L167

Note that it's not part of our public API, though; if you want to call it, let us know and we can declare it public.

Simplecov just calls `exit`, so that might not be so bad, though:

https://github.com/colszowka/simplecov/blob/994dbff2780abe420f63036a7f674c296395b6c0/lib/simplecov.rb#L206

**Comment by ioquatix** [comment]
Here is what I have:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/30030/42193232-7715c81c-7ec1-11e8-8237-f0495a9c48bc.png">

Ideally, I can bump the failure count up by one some how, e.g.

```
35 examples, 0 failures, x coverage errors
```

**Comment by ioquatix** [comment]
`RSpec.configuration.reporter.notify_non_example_exception` sort of works, but it forces me to use an exception. It's not stupid though.

I wonder if it's possible to append some failure state, e.g.

```
module Covered
	module RSpec
		class Formatter
			::RSpec::Core::Formatters.register self, :dump_summary
			
			def initialize(output)
				@output = output
			end
			
			def dump_summary notification
				@output << $/
				
				$covered.print_summary(@output)
				
				notification.failure("x coverage issues")
			end
		end
	end
end
```

the key point being `notification.failure` to feed information back.

**Comment by ioquatix** [comment]
One more thing - is there any way to tell if the full test suite is being run vs only a subset?

**Comment by myronmarston** [comment]
> RSpec.configuration.reporter.notify_non_example_exception sort of works, but it forces me to use an exception. 

You can print anything you want to the console, so if that doesn't meet your needs print whatever does meet your needs.

> One more thing - is there any way to tell if the full test suite is being run vs only a subset?

Nothing built in to RSpec.

I'm going to close this as there's nothing actionable for us do to change RSpec here.

**Comment by ioquatix** [comment]
Fair enough :) Thanks for your help.

Is there any other way to bump the failure count, other than `RSpec.configuration.reporter.notify_non_example_exception`?

**Comment by myronmarston** [comment]
> Is there some way just to say "something failed"? 

`puts "something failed"`

**Comment by JonRowe** [comment]
To bump up the failure count you need to define an example that is run, and fails, to exit non zero you simply need to cause an exception. If you raise an error with no back trace, no back trace would be printed.
