### ISSUE TITLE
Yard should work on Ruby 2.7

### ISSUE THREAD

**Issue by benoittgt** [rspec/rspec-dev#231]
See: https://github.com/rspec/rspec-dev/pull/230#discussion_r361809017

Locally, I tried to run :

```sh
benoit:rspec-core/ (master) $ which yard                                                                                                                                   
/Users/bti/.rvm/gems/ruby-2.7.0-preview1/bin/yard
```

Then
```
bti:rspec-core/ (master) $ yard
The dependency jruby-openssl (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Files:          33
Modules:        18 (    0 undocumented)
Classes:        36 (    0 undocumented)
Constants:       5 (    0 undocumented)
Attributes:     85 (    0 undocumented)
Methods:       252 (    0 undocumented)
 100.00% documented
```

@JonRowe where do we have the issue?

**Comment by JonRowe** [comment]
@benoittgt see #232 and rspec/rspec-mocks#1307

**Comment by pirj** [comment]
Leaving it here for the reference https://github.com/lsegal/yard/pull/1296

**Comment by pirj** [comment]
How [RuboCop worked around this](https://github.com/rubocop-hq/rubocop/pull/7598/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R12):
```diff
# Gemfile
+    gem 'e2mmap'
```

I believe this is due to [`e2mmap` stopped being bundled](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/):
> The following libraries are no longer bundled gems. Install corresponding gems to use these features.

I'd rather wait/implement a `yard` fix rather than working around this since it's not required in runtime.

**Comment by benoittgt** [comment]
I think we should wait for this patch to get merged https://github.com/lsegal/yard/pull/1296

**Comment by benoittgt** [comment]
Close in favor of https://github.com/rspec/rspec-dev/issues/232
