### ISSUE TITLE
Default configurations around coverage criteria and minimum coverage

### ISSUE THREAD

**Issue by ritikesh** [rspec/rspec-dev#312]
Are there any reasons why branch coverage and 100% minimum coverage aren't the default configurations when using simplecov?

**Comment by pirj** [comment]
Yes, limited time. PRs to improve coverage ate welcome.
However, we have RSpec 4 telease in mind and we’re thinking of putting all libs to a monorepo. If you take a look at the RSpec 4 plan, increasing coverage to a maximum is there, and there’s also an rspec-core ticket.

**Comment by ritikesh** [comment]
@pirj apologies, I intended to post this issue in the simplecov repository, wondering why new projects that use simplecov don't default to branch criteria with a 100% coverage as configuration.. in my exploration, looks like I accidentally posted it here which made it look like a question on the maintenance of the project itself. Apologies for that. I will checkout the rspec 4.0 trajectory and will contribute as possible. Thanks.
