### ISSUE TITLE
Ideas to improvements to travis builds

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-dev#45]
I've had a few ideas rattling around in my brain for ways we can improve the travis builds for the rspec gems...

Occasionally, a change to rspec-mocks breaks the rspec-expectations or rspec-core build.  Or the change to rspec-core breaks one of the others, etc.  We don't usually notice right away.  It would be nice to improve our build process to catch this.  So I was thinking we could add a post-processing step to our travis builds for each gem that runs the spec suite for the _other_ rspec gems to surface issues early.  No need to run the full build suite (i.e. including cukes) for this; that would add a lot of build time without much benefit.  The specs for each are quite fast and would give us some nice quick feedback.

Occasionally, a change causes a performance regression.  We may or may not notice.   It would be nice if there was a part of the build that noticed such things and notified us. To that end, we could add a step that runs a shell command like this:

```
time (for i in {1..20}; do bin/rspec -fp --order default; done)
```

...and then checks out master and repeats that command, then compares the two times, and if the time of the new commit is more than x% slower than master's time, fail the build.

Thoughts?

/cc @alindeman @JonRowe @dchelimsky @soulcutter @samphippen

**Comment by pirj** [comment]
I think we trigger specs for siblings
