### ISSUE TITLE
New Gems aren't listed in README

### ISSUE THREAD

**Issue by JonRowe** [rspec/rspec-dev#49]
As per rspec/rspec-collection_matchers#8 the new gems aren't yet listed in the readme here. We should fix that. 

Thanks to @palfvin for reporting as per:

> Not sure what the convention is for issues that cross repositories, but the README file for rspec-dev does not include this gem currently. Instead of having to keep the README in lock step with the repo structure, the README could be modified so that it doesn't need to give an exact description of the structure.

**Comment by benoittgt** [comment]
Is it still something we want to do or it could be closed?

**Comment by JonRowe** [comment]
If you'd like to tackle it @benoittgt?

**Comment by benoittgt** [comment]
Closed by https://github.com/rspec/rspec-dev/pull/226
