### ISSUE TITLE
Get windows CI builds going

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-dev#83]
http://www.appveyor.com/ provides a travis-like CI service.  It's free for open source and runs on windows.  I noticed that byebug is using it for windows builds:

https://github.com/deivid-rodriguez/byebug/commit/3c523bddf1a5d6382dfa60698229ec8aa8326232
https://ci.appveyor.com/project/deivid-rodriguez/byebug

Given we've had some recent windows problems, I think it's worth trying to get a windows CI build going.

**Comment by rsanchez79** [comment]
@myronmarston did you modify the build settings thru the appveyor web site. If I use the project as is, I get this error: 

1 Build started
2 git clone -q git://github.com/rspec/rspec-core.git C:\projects\rspec-core
3 git fetch -q origin +refs/pull/1760/merge:
4 git checkout -qf FETCH_HEAD
5 Specify a project or solution file. The directory does not contain a project or solution file.

I have windows machines at home and work so hopefully I can help with this issue.

**Comment by myronmarston** [comment]
> @myronmarston did you modify the build settings thru the appveyor web site.

Nope.  Our build settings are in `appveyor.yml` in each repo (which is centrally managed and pushed out from this repo).  For example, here's rspec-core's:

https://github.com/rspec/rspec-core/blob/master/appveyor.yml

Notice that we have `build: off` which disables the normal appveyor build (which I guess assumes a .NET project or solution file?).  Instead we have `test_script` specified.

All that said: I wouldn't worry too much about running the build the same as AppVeyor runs it, unless you've found differences in what passes on AppVeyor compared to what passes locally for you.  I suspect that the failures aren't AppVeyor specific (except perhaps the issue mentioned above with getting cucumber to run), so I'd start by seeing what fails for you and addressing those.

> I have windows machines at home and work so hopefully I can help with this issue.

:heart: :heart:  Fantastic!  Thanks for giving this a shot!  It's a huge help.

**Comment by olleolleolle** [comment]
👋 Hi, I would like to ask, are there more Windows CI build things still extant, now that there is a `window:` section of the GH Actions configuration?

https://github.com/rspec/rspec-dev/blob/main/ci/.github/workflows/ci.yml#L123

**Comment by pirj** [comment]
Thanks for bringing this up, @olleolleolle !
